FROM node:20-slim

WORKDIR /app

COPY client/package.json client/package-lock.json ./
RUN npm install

COPY client/ .

EXPOSE 3000

ENV NEXT_DISABLE_TURBOPACK=1

CMD ["npm", "run", "dev"]
